[book]
authors = ["pointertobios"]
language = "en"
src = "src"
title = "ASCO Coroutine Async Framework"

[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/pointertobios/asco"
hash-files = true
